apps/accounts/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls import url

from . import views

app_name = "accounts"

urlpatterns = [
    url(r'^login/$', views.user_login, name='login'),
    url(r'^register/$', views.user_register, name='register'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^account/$', views.account, name='account'),
    url(r'^change_account/$', views.change_account, name='change_account'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change_username/$', views.change_username, name='change_username'),
    url(r'^change_mugshot/$', views.change_mugshot, name='change_mugshot'),
    url(r'^about', views.about, name='about'),
]

apps/notes/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'note'
urlpatterns = [
    # homepage
    path(r'', views.index, name='index'),
    url(r'^edit_note/$', views.edit_note, name='edit_note'),
    url(r'^store_note/$', views.store_note, name='store_note'),
    url(r'^like_note$', views.like_note, name='like_note'),
    url(r'^note_detail/(?P<id>[0-9]+)/$', views.detail, name='note_detail'),
    url(r'^comment/$', views.comment, name='comment'),
    url(r'^wishlist/$', views.wishlist, name='wishlist'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('apps.notes.urls', namespace='note')),
    url(r'', include('apps.accounts.urls', namespace='account')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now


# Create your models here.

class UserAccount(AbstractUser):
    nickname = models.CharField('Name', max_length=100, blank=True)
    mugshot = models.ImageField('Photo', upload_to='upload/mugshots', blank=True,
                                default='upload/mugshots/logo.jpg')
    created_time = models.DateTimeField('Create Time', default=now)
    last_mod_time = models.DateTimeField('Modify Time', default=now)

    # objects = BlogUserManager()
    def __str__(self):
        return self.email

apps/notes/models.py
from datetime import datetime

from django.db import models

from django.contrib.auth.models import AbstractUser

from apps.accounts.models import UserAccount


# Create your models here.
class Note(models.Model):
    content = models.CharField(max_length=800, verbose_name="content", default='')
    cover = models.ImageField(upload_to="image/%Y/%m", max_length=100, default='')
    tag = models.CharField(max_length=256, null=True, verbose_name='tags')
    like_count = models.IntegerField(default=0, verbose_name='like_count')
    user = models.ForeignKey(UserAccount, to_field='id', default=0, on_delete=True, verbose_name="user_id")
    created_at = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = "note"

    def __unicode__(self):
        return self.content

    def like(self):
        self.like_count += 1
        self.save()

    def unlike(self):
        self.like_count -= 1
        self.save()

    def comment_list(self):
        comments = NoteComment.objects.filter(note=self)
        return comments


class NoteComment(models.Model):
    user = models.ForeignKey(UserAccount, to_field='id', default=0, on_delete=True, verbose_name="user_id")
    note = models.ForeignKey(Note, verbose_name="note_id", on_delete=True)
    comment = models.CharField(max_length=300, verbose_name="comment")
    created_at = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = "comment"


class WishList(models.Model):
    user = models.ForeignKey(UserAccount, to_field='id', default=0, on_delete=True, verbose_name="user_id")
    note = models.ForeignKey(Note, verbose_name="note_id", on_delete=True)
    created_at = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = "wishlist"

apps/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.decorators import login_required

from apps.accounts.models import UserAccount


# Create your views here.
def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username', "")
        password = request.POST.get('password', "")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            message = "Authenticate failed. Please check username or password!"
            return render(request, 'login.html', {"message": message})
        pass
    elif request.method == "GET":
        return render(request, 'login.html')


def user_register(request):
    if request.method == "POST":
        username = request.POST.get('username', "")
        email = request.POST.get('email', "")
        password = request.POST.get('password', "")
        password = make_password(password)
        if UserAccount.objects.filter(username=username):
            return render(request, 'register.html', {"message": "User has already existed"})
        user = UserAccount.objects.create(username=username, email=email, password=password)
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return HttpResponseRedirect('/')
    elif request.method == "GET":
        return render(request, 'register.html')


def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect('/')


def about(request):
    return render(request, 'about.html')


@login_required
def account(request):
    return render(request, 'account.html')


@login_required
def change_account(request):
    return render(request, 'account_update.html')


@login_required
def change_password(request):
    user = request.user
    old_password = request.POST.get('oldPassword')
    password = request.POST.get('newPassword')
    re_password = request.POST.get('rePassword')
    if password != re_password:
        msg = 'Please Confirm Your Password! password is different'
        return render(request, 'account_update.html', {'msg': msg})
    if check_password(old_password, user.password):
        user.password = make_password(password)
        user.save()
        return HttpResponseRedirect('/login')
    else:
        msg = 'Old password is wrong!'
        return render(request, 'account_update.html', {'msg': msg})


@login_required
def change_username(request):
    user = request.user
    username = request.POST.get('username')
    user_existed = UserAccount.objects.filter(username=username).first()
    if user_existed is not None:
        msg = 'username ' + username + 'already exists'
        return render(request, 'account_update.html', {'msg': msg})
    else:
        user.username = username
        user.save()
        return HttpResponseRedirect('/change_account')


@login_required
def change_mugshot(request):
    file = request.FILES.get('userPhoto')
    user = request.user
    user.mugshot = file
    user.save()
    print(user.mugshot)
    return HttpResponseRedirect('/change_account')

apps/notes/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, JsonResponse

from apps.notes.models import Note, WishList, NoteComment


# Create your views here.

def index(request):
    notes = Note.objects.all().order_by('-id')
    for note in notes:
        if request.user.is_authenticated:
            wish = WishList.objects.filter(user=request.user, note=note).first()
            if wish is not None:
                note.is_up = True
            else:
                note.is_up = False
        else:
            note.is_up = False
    return render(request, 'home.html', {"notes": notes})


def edit_note(request):
    return render(request, 'edit_note.html')


def detail(request, id):
    note = Note.objects.get(id=id)
    if request.user.is_authenticated:
        wish = WishList.objects.filter(user=request.user, note=note).first()
        if wish is not None:
            note.is_up = True
        else:
            note.is_up = False
    else:
        note.is_up = False
    return render(request, 'note.html', {'note': note})


@login_required
def store_note(request):
    note_pic = request.FILES.get('notePic')
    note_content = request.POST.get('noteContent')
    Note.objects.create(cover=note_pic, content=note_content, user=request.user)

    return HttpResponseRedirect('/')


@login_required
@csrf_exempt
def like_note(request):
    note_id = request.POST.get('id')
    note = Note.objects.get(id=note_id)
    wish_list = WishList.objects.filter(user=request.user, note=note).first()
    if wish_list is not None:
        wish_list.delete()
        result = 0
        note.unlike()
    else:
        WishList.objects.create(user=request.user, note=note).save()
        result = 1
        note.like()

    res = {
        "success": True,
        "result": result,
        "message": 'success'
    }

    return JsonResponse(res)


@login_required
def comment(request):
    comment = request.POST.get('comment')
    noteId = request.POST.get('noteId')
    note = Note.objects.get(id=noteId)
    NoteComment.objects.create(user=request.user, note=note, comment=comment)
    return HttpResponseRedirect('/note_detail/' + noteId)


@login_required
def wishlist(request):
    wishlist = WishList.objects.filter(user=request.user)
    return render(request, 'wishlist.html', {"wishlist": wishlist})

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <div class="main note">
        <div class="jumbotron" style="background-color: #fff6f4">
            <h1 class="display-3">Hello, this is about page!</h1>
            <br><br>
            <p class="lead">2349520w@student.gla.ac.uk</p>
            <p class="lead">2359448y@student.gla.ac.uk</p>
            <p class="lead">2411335z@student.gla.ac.uk</p>
            <p class="lead">2359514z@student.gla.ac.uk</p>
            <br><br>
            <hr class="my-4">
            <p>Welcome to our website!</p>
        </div>
    </div>

    </body>
{% endblock %}
</html>

templates/account_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %}
    MyAccount
{% endblock %}

{% block body_block %}
    <style>
        .form {
            width: 24%;
            margin-right: 4%;
            color: #666;
        }


        .form label {
            display: block;
            padding-bottom: 7px;
        }

        .form input {
            width: 100%;
            height: 50px;
            padding-left: 5px;
            padding-right: 5px;
            border: 1px solid rgb(186, 186, 186);
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
        }

        .form-btns {
            margin: 20px auto;
            overflow: hidden;
            position: relative;
        }

        .form-btns button, #btnChooseImg {
            display: block;
            text-decoration: none;
            text-align: center;
            width: 46%;
            line-height: 40px;
            font-size: 17px;
            color: white;
            background: rgb(123, 193, 173);
            border-radius: 10px;
            outline: none;
            border: 0;
            cursor: pointer;
        }

        .photo-box {
            width: 100%;
            /* max-width: 300px; */
            height: 0;
            padding-bottom: 100%;
            overflow: hidden;
        }

        .user-photo {
            width: 100%;
            /* max-width: 300px; */
            /* max-height: 300px; */
        }

        #btnChooseImg {
            position: absolute;
            opacity: 0;
            cursor: pointer;
        }
    </style>

    <body>

    <div class="main">
        <!-- update password -->
        <div class="pull-left form">
            <form autocomplete="off" action="{% url 'account:change_password' %}" method="post">
                {% csrf_token %}

                <div class="form-group">
                    <fieldset>
                        <label class="control-label hide" for="oldPassword">Old Password:</label>
                        <input type="password" class="form-control" name="oldPassword" id="oldPassword"
                               placeholder="Old Password">
                    </fieldset>
                </div>

                <div class="form-group">
                    <fieldset>
                        <label class="control-label" for="newPassword">New Password:</label>
                        <input type="password" class="form-control" name="newPassword" id="newPassword"
                               placeholder="New Password">
                    </fieldset>
                </div>

                <div class="form-group">
                    <fieldset>
                        <label class="control-label" for="rePassword">Confirm New Password:</label>
                        <input type="password" class="form-control" name="rePassword" id="rePassword"
                               placeholder="Confirm New Password">
                    </fieldset>
                </div>

                <button type="submit" class="btn btn-primary">Update Password</button>
                <p style="color: red">{{ msg }}</p>
            </form>

        </div>
        <!-- update username -->
        <div class="pull-left form">
            <form action="{% url 'account:change_username' %}" method="post">
                {% csrf_token %}

                <div class="form-group">
                    <label class="col-form-label" for="username">Change Username:</label>
                    <input type="text" class="form-control" placeholder="Please input a username" name="username"
                           id="username">
                </div>

                    <button type="submit" class="btn btn-primary">Update username</button>

            </form>
        </div>
        <!-- update photo -->
        <div class="pull-left form">
            <form action="{% url 'account:change_mugshot' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>Change Profile Photo:</label>
                    <div class="photo-box">
                        <img id="userPhoto" class="user-photo" src="/media/{{ request.user.mugshot }}" alt="ProfilePhoto">
                    </div>
                </div>

                <div class="form-btns">
                    <input id="btnChooseImg" name="userPhoto" type="file" accept="image/*"/>
                    <button type="submit" class="pull-left">Choose img</button>

                    <button type="submit" class="pull-right">Update img</button>
                </div>
            </form>
        </div>
    </div>

    </div>

    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script>
        var fileInput = $('#btnChooseImg');
        var userImg = $('#userPhoto');

        fileInput.change(function () {
            var objUrl = getObjectURL(this.files[0]);
            console.log("objUrl = " + objUrl);
            if (objUrl) {
                userImg.attr("src", objUrl);
            }
        })

        function getObjectURL(file) {
            var url = null;
            if (window.createObjectURL != undefined) { // basic
                url = window.createObjectURL(file);
            } else if (window.URL != undefined) { // mozilla(firefox)
                url = window.URL.createObjectURL(file);
            } else if (window.webkitURL != undefined) { // webkit or chrome
                url = window.webkitURL.createObjectURL(file);
            }
            return url;
        }
    </script>
    </body>
{% endblock %}
</html>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head lang="en">
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <title>
        BeautyNote-
        {% block title_block %}

        {% endblock %}
    </title>

    <style>
        body {
            background: rgb(255, 227, 230);
        }
    </style>

</head>

<body>

<div class="section header">
    <div class="pull-left account h2">
        <img src="/static/images/logo.jpg" alt="">
        <a href="/"><img style="width: 250px" src="/static/images/title.png" alt=""></a>
    </div>
    {% if request.user.is_authenticated %}
        <div class="pull-right">

            <a href="/edit_note"><button type="button" class="btn btn-link">Publish Note</button></a>

            <a href="/wishlist"><button type="button" class="btn btn-link">Wish List</button></a>

            <a href="/account"><button type="button" class="btn btn-link">MyAccount</button></a>

            <a href="/logout"><button type="button" class="btn btn-link">Logout</button></a>

        </div>

    {% else %}
        <div class="pull-right link">
            <a href="/login"><button type="button" class="btn btn-link">Login</button></a>
            <a href="/register"><button type="button" class="btn btn-link">Register</button></a>
        </div>
    {% endif %}
</div>


<div>
    {% block body_block %}
    {% endblock %}
</div>

<div class="section footer">
    <div class="link" style="text-align: center">
         <a href="/about.html"><button type="button" class="btn btn-link" style="font-size: 20px">About&Contact Us</button></a>
    </div>
</div>

</body>

</html>

templates/edit_note.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %}
    EditNote
{% endblock %}

{% block body_block %}
    <style>

        .form {
            color: #666;
        }


        .form label {
            display: block;
            padding-bottom: 7px;
        }

        .form input {
            width: 100%;
            height: 50px;
            padding-left: 5px;
            padding-right: 5px;
            border: 1px solid rgb(186, 186, 186);
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
        }

        .form-btns {
            margin: 20px auto;
            overflow: hidden;
            position: relative;
        }

        .form-btns button, #btnChooseImg {
            display: block;
            text-decoration: none;
            text-align: center;
            width: 46%;
            max-width: 200px;
            line-height: 40px;
            font-size: 18px;
            color: white;
            background: rgb(123, 193, 173);
            border-radius: 10px;
            outline: none;
            border: 0;
            cursor: pointer;
        }


        #noteImg {
            width: 26%;
        }

        #btnChooseImg {
            position: absolute;
            opacity: 0;
            cursor: pointer;
        }

        #noteContent {
            width: 94%;
            height: 120px;
            padding: 5px;
            border-radius: 3px;
        }
    </style>
    </head>
    <body>

    <div class="main">
        <div class="form" style="padding-left: 50px">
            <form action="{% url 'note:store_note' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <img id="noteImg" src="" alt="">
                <div class="form-btns">
                    <input id="btnChooseImg" name="notePic" type="file" accept="image/*"/>
                    <button type="submit" class="btn btn-primary">Choose Picture</button>
                </div>

                <div class="form-group">
                    <textarea class="form-control" name="noteContent" id="noteContent"
                              placeholder="Write your note here" rows="10" style="height: 300px"></textarea>
                </div>
                <div class="form-btns" style="padding-right: 10%;">
                    <button type="submit" class="pull-right">Publish</button>
                </div>
            </form>
    </div>

    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script>
        var fileInput = $('#btnChooseImg');
        var userImg = $('#noteImg');

        fileInput.change(function () {
            var objUrl = getObjectURL(this.files[0]);
            if (objUrl) {
                userImg.attr("src", objUrl);
            }
        })

        function getObjectURL(file) {
            var url = null;
            if (window.createObjectURL != undefined) { // basic
                url = window.createObjectURL(file);
            } else if (window.URL != undefined) { // mozilla(firefox)
                url = window.URL.createObjectURL(file);
            } else if (window.webkitURL != undefined) { // webkit or chrome
                url = window.webkitURL.createObjectURL(file);
            }
            return url;
        }
    </script>
    </body>
{% endblock %}
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %}
    Home
{% endblock %}

{% block body_block %}
    <style>
        .notes {
            overflow: hidden;
        }

        .note-item {
            display: block;
            text-decoration: none;
            width: 25%;
            padding: 14px;
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
        }

        .n-item-inner {
            padding: 14px;
            background: white;
            border-radius: 50px;
            overflow: hidden;
            border: 1px solid #ccc;
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
        }

        .n-img img {
            width: 100%;
            border-radius: 50px;
        }

        .n-intro {
            padding: 4px 0;
            font-size: 15px;
            color: #444;
            word-break: break-all;
            line-height: 20px;
            height: 40px;
            overflow: hidden;
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
        }

        .n-user {
            color: #666;
            font-size: 13px;
            height: 50px;
            line-height: 50px;
            overflow: hidden;
        }

        .n-user img {
            width: 30px;
            height: 30px;
            vertical-align: middle;
        }

        .userinfo {
            max-width: 65%;
        }

        .userinfo span {
            display: inline-block;
            max-width: 70%;
            text-overflow: ellipsis;
            overflow: hidden;
            vertical-align: middle;
            white-space: nowrap;
        }

        .userinfo img {
            width: 40px;
            height: 40px;
            margin-right: 3px;
        }

        .link-note {
            color: white;
            font-size: 17px;
            height: 34px;
            line-height: 34px;
            text-decoration: none;
            padding: 0 17px;
            margin: 23px;
            background: rgb(230, 160, 109);
            border-radius: 20px;
            border: 1px solid #999;
        }
    </style>
<body>

<div class="main notes">
    <!-- item -->
    {% for note in notes %}
        <a href="{% url 'note:note_detail' note.id %}" class="note-item">
        <div class="n-item-inner">
            <div class="n-img">
                <img src="/media/{{ note.cover }}" alt="picture">
            </div>
            <p class="n-intro">{{ note.content }}</p>
            <div class="n-user">
                <div class="pull-left userinfo">
                    <img src="/media/{{ note.user.mugshot }}" alt="">
                    <span>{{ note.user.nickname }}</span>
                </div>
            {% if request.user.is_authenticated %}
                <div class="pull-right n-likes">
                    <!-- item id -->
                    <input value="{{ note.id }}" type="hidden">
                    {% if note.is_up %}
                        <img src="/static/images/liked.png" alt="">
                    {% else %}
                        <img src="/static/images/inlike.png" alt="">
                    {% endif %}
                    <span>{{ note.like_count }}</span>
                </div>
            {% else %}
                <div class="pull-right">
                    <!-- item id -->
                    <input value="{{ note.id }}" type="hidden">
                    {% if note.is_up %}
                        <img src="/static/images/liked.png" alt="">
                    {% else %}
                        <img src="/static/images/inlike.png" alt="">
                    {% endif %}
                    <span>{{ note.like_count }}</span>
                </div>
            {% endif %}
            </div>
        </div>
    </a>
    {% endfor %}
</div>

<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/js/masonry.pkgd.min.js"></script>
<script src="/static/js/imagesloaded.pkgd.min.js"></script>
<script>
    var requesting = false;
    var $grid = $('.notes').masonry({
        itemSelector: '.note-item',
        columnWidth: '.note-item',
        percentPosition: true
    });
    $grid.imagesLoaded().progress(function () {
        $grid.masonry('layout')
    });

    $(document).on('click', '.n-likes', function (e) {
        var $item = $(this);
        e.preventDefault();
        e.stopPropagation();
        if (requesting) return;
        requesting = true;

        $.ajax({
            url: '/like_note',
            type: 'post',
            data: {
                id: $item.find('input').val()
            },
            success: function (res) {
                console.log(res)
                if (!res.success) {
                    alert(res.message);
                    return
                }
                if (res.result == 1) {
                    $item.find('img').attr('src', '/static/images/liked.png')
                } else {
                    $item.find('img').attr('src', '/static/images/inlike.png')
                }
            },
            error: function (xhr, type) {
                alert('Internet exception: ' + type)
            },
            complete: function () {
                requesting = false
            }
        })
    })
</script>
</body>
{% endblock %}

</html>

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <style>


        .form-login {
            width: 40%;
            color: #666;
        }

        .input-group {
            margin-bottom: 17px;
        }

        .form-login label {
            display: block;
            padding-bottom: 7px;
        }

        .form-login input {
            width: 100%;
            height: 50px;
            padding-left: 5px;
            padding-right: 5px;
            border: 1px solid rgb(186, 186, 186);
            box-sizing: border-box;
            -webkit-box-sizing: border-box;
        }

        .form-btns {
            margin: 20px auto;
            overflow: hidden;
        }

        .form-btns button {
            display: block;
            text-decoration: none;
            text-align: center;
            width: 46%;
            height: 45px;
            line-height: 40px;
            font-size: 17px;
            color: white;
            background: rgb(123, 193, 173);
            border-radius: 10px;
            border: 0;
        }

        .form-btns a {
            display: block;
            text-decoration: none;
            text-align: center;
            width: 46%;
            height: 45px;
            line-height: 45px;
            font-size: 17px;
            color: white;
            background: rgb(123, 193, 173);
            border-radius: 10px;
            border: 0;
            padding: 0;
        }

        .login-facebook {
            width: 45%;

        }

        .mid-separator {
            position: relative;
            width: 10%;
            height: 340px;
            text-align: center;

        }

        .separator {
            margin-top: 145px;
            display: inline-block;
            width: 50px;
            height: 50px;
            text-align: center;
            line-height: 50px;
            color: rgb(186, 186, 186);
            border: 1px solid rgb(186, 186, 186);
            border-radius: 50%;

        }

        .separator::before, .separator::after {
            content: '';
            position: absolute;
            width: 1px;
            height: 144px;
            bottom: 0;
            left: 50%;
            background: rgb(186, 186, 186);

        }

        .separator::before {
            top: 0;
        }

        .btn-facebook {
            display: inline-block;
            text-decoration: none;
            height: 50px;
            line-height: 50px;
            padding-left: 10px;
            padding-right: 40px;
            margin-top: 145px;
            font-weight: 600;
            color: white;
            background: #ad7e7d;
            border-radius: 3px;
        }

        .btn-facebook img {
            width: 40px;
            height: 40px;
            vertical-align: middle;
        }
    </style>
</head>
<body>

<div class="main" style="padding-left: 120px;padding-top: 120px">
    <div class="pull-left form-login">
        <form action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username">
            </div>
            <div class="input-group">
                <label for="password">Password:</label>
                <input type="text" name="password" id="password">
            </div>
            <div class="form-btns">
                <button class="pull-left" type="submit">Login</button>
                <a class="pull-right" href="{% url 'account:register' %}">Create an account</a>
            </div>
        </form>
        <p style="color: red">{{ message }}</p>
    </div>
    <div class="pull-left mid-separator">
        <div class="separator">OR</div>
    </div>
    <div class="pull-left login-facebook">
        <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn-facebook">
            <img src="/static/images/google.png" alt="">
            <span>Login with Google</span>
        </a>
    </div>
</div>

</body>
{% endblock %}

</html>